# docker-compose.yml

version: "3.8"

services:
  backend:
    build: ./server
    container_name: reembolsabb_backend
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: reembolsabb_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=reembolsabb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
